---
title: "obesity"
author: "Walter Guillioli"
date: "2025-06-02"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

rm(list = ls())

require(tidyverse)
require(corrplot)
require(naniar) #visualize missing values


```

```{r load_data}

project_dir <- "C:/GitHub/obesity/"

train <- read_csv(paste0(project_dir, "data/train.csv"))
dim(train) # 20758    18
glimpse(train)

test <- read_csv(paste0(project_dir, "data/test.csv"))
dim(test) # 13840    17
glimpse(test)

```

```{r create_dataset}

train$source <- "train"
test$source <- "test"

test$NObeyesdad <- NA

d <- bind_rows(train, test)
dim(d) #34598    19

```

```{r missing_values} 

vis_miss(d[,1:17])

sum(is.na(d[, 1:17]))

#apply(d, sum(is.na, NA))

```



```{r target_var}

d %>%
  filter(source == "train") %>%
  group_by(NObeyesdad) %>%
  summarise(n = n()) %>%
  mutate(prop = round(n/sum(n),2))

```

```{r eda_predictors}

#is_num_flag <- sapply(d, is.numeric)
#glimpse(d[is_num_flag])

numeric_vars <- c("Age", "Height", "Weight", "FCVC", 
                  "NCP", "CH2O", "FAF", "TUE")

glimpse(d[,numeric_vars])

#is_chr_flag <- sapply(d, is.character)
#glimpse(d[is_chr_flag])

character_vars <- c("Gender", "family_history_with_overweight", "FAVC", "CAEC", 
                    "SMOKE", "SCC", "CALC", "MTRANS")

glimpse(d[,character_vars])
#VOY

```

univ prep chr y pot pred

```{r eda_chr}

glimpse(d[,character_vars])


```



univ prep num y pot pred

multicolinearity






```{r}

corrplot(round(cor(d[,numeric_vars]),2))


```

REFERENCES

https://www.kaggle.com/competitions/playground-series-s4e2/data
https://www.kaggle.com/datasets/aravindpcoder/obesity-or-cvd-risk-classifyregressorcluster/data


